### PR TITLE
Fix the wrong display of settingsFile path.

### LINKED ISSUE #337: SettingsFiles path is not displayed with correct slashes on Windows.
### Prerequisites

- [x] I'm using latest version: v0.18.0 

### Description

[Description of the issue]

Operating system: Windows 10.0.17134 Build 17134

### Steps to Reproduce

1. Open About dialog.

**Expected behavior:** 
The settings file path should be like C:\Users\XXX\AppData\Roaming\stretchly\config.json

**Actual behavior:** 
settingsFile: C:\Users\XXX\AppData\Roaming\stretchly/config.json
The last separator should be a backslash on Windows, however, it is a forward slash.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### PR DESCRIPTION
**Pull request by xinxuzhang**
Issue: closes #337

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [ ]  issue was opened to discuss proposed changes before starting implementation.
- [ ]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [ ]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [ ]  app version number was not changed.
- [ ]  all new code has tests to ensure against regressions.
- [ ] `npm run lint` reports no offenses.
- [ ] `npm run test` is error-free.
- [ ]  README and CHANGELOG were updated accordingly.

### CODE REVIEW

**Comment by hovancik** [comment]
Cool ;] Did you test it by running app?  

You can also add yourself to readme ;] https://github.com/hovancik/stretchly#contributors

**Comment by xinxuzhang** [comment]
Sorry, I cannot build it on my PC, it kept reporting error during this step "stretchly@0.18.0 postinstall: `electron-builder install-app-deps`", I think it must be due to my environment configuration or something else, I didn't dig into it.
I have built it on my Mac, and everything works fine.

**Comment by xinxuzhang** [comment]
As it is really a minor change, I think there is no necessary to add me to the contributors.

**Comment by hovancik** [comment]
Can't force you :D

**Pull request merged**
