### PR TITLE
Minor copy editing

### PR DESCRIPTION
**Pull request by lclarke522**
Proofread README as requested in the newsletter. There are several places where I could have inserted "the" (as in "change the language" instead of "change language"). I didn't do it, because I wasn't sure if it was a stylistic choice to leave them out. If you'd like me to go back and add the "the" articles where they should be, let me know!

Issue: #

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [ ]  issue was opened to discuss proposed changes before starting implementation.
- [ ]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [ ]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [ ]  app version number was not changed.
- [ ]  all new code has tests to ensure against regressions.
- [ ] `npm run lint` reports no offenses.
- [ ] `npm run test` is error-free.
- [x]  README and CHANGELOG were updated accordingly.

### CODE REVIEW

**Comment by hovancik** [comment]
Hi @lclarke522 and thanks so much for the edits ;] English is not my first language so leaving `the` was definitely not any stylistic choice ;] If you could fix that, that would be awesome. 

Let me know if you can edit your current PR, otherwise I can merge this one and you can create new one.

**Comment by lclarke522** [comment]
I'm not actually sure how to edit the PR. You could tell me how, or I can jut submit a new one. Either way :-)

**Comment by hovancik** [comment]
I am not sure as well, never tried, but it looks like you should be able to click on "Files Changed" and then (...) and then edit. 

image

If you don't have that option, I will merge this one and you can create new one.

**Comment by lclarke522** [comment]
Ah, yes, there it is. I can edit from there. I'll work on it again later today :-)

**Comment by lclarke522** [comment]
Sorry, I forgot to get back to this yesterday 😬 

I have a question about this line:
> Note that when a new *Stretchly* version with new break ideas is out, your custom ideas won't get updated.

Does it mean that your custom ideas _will_ be overwritten or they _won't_ be overwritten?

**Comment by hovancik** [comment]
Yes, it means that they will not be overwritten :)

**Pull request merged**
