### PR TITLE
Add ability to postpone breaks

### PR DESCRIPTION
**Pull request by lundibundi**
* allow postponing breaks in non-strict mode (break/microbreak Postpone)
* adjustable postpone time (break/microbreak PostponeTime)
* after a configurable number of postpones show skip button instead of postpone
  (0 for infinite postpone) (break/microbreak PostponesLimit)

Also currently there is no option in Settings for Postpone because I'm not sure for which ones to put there as I would like to get your opinion on this.

This is my first time working with electron so I hope I got everything right.

UPD: I've got an idea to use negative postponeLimit numbers to note that break must become strict after that amount of postpones, what do you think about it? (or use positive for this purpose and negative when we allow skipping the break) Or just add another option for such behavior.

fixes: https://github.com/hovancik/stretchly/issues/161

### CODE REVIEW

**Comment by lundibundi** [comment]
CI failure on mac seems unrelated to me.

**Comment by hovancik** [comment]
Hi,  I'm going for holidays now, so not sure if I manage to take a look before I leave, so please be patient. I'll be coming back at the end of the April.

**Comment by lundibundi** [comment]
@hovancik Have a good holiday =). I'd also like to get your opinion on https://github.com/hovancik/stretchly/issues/152#issuecomment-376507773 as I wanted to implement it this way before you go if possible.

**Comment by hovancik** [comment]
@lundibundi I'm still not decided how to do about idle time detection, so please do not implement anything, yet.

**Comment by hovancik** [comment]
Hey, so I am trying it right now. 

My first thoughts:  
- I would only allow to edit settings by manually editing config file (I want to keep settings simple, and I do not think we need  this settings on Settings page - the most of people I talked to never change any settings)
- skipping should be enabled by default
- number of allowed skips should be one (yeah, let's be harsh ;] )

In the beginning I didn't like the fact that you are changing "skip" for "postpone" - reason being I thought user should have both options. And also I wanted to recommend another solution: user can postpone break by clicking on break notification. But I am beginning to like your solution: it's more educational  and breaks should be more often if users postpone once than skipping. I will think more about it. Also not sure what about times: 2 and 5 minutes. Maybe both as 2 minutes? 

Also: in future, I want to have idle time detection ala: when break is about to start, we will wait some time until user is idle and then start the break. So this is also something to keep in mind. 

For your UPD question:  
I've implemented (long long time ago) https://github.com/hovancik/stretchly/tree/feature/dangerous-breaks which works kinda like this: it counts number of skipped breaks and increases a variable, when break is not skipped it decreases the number. Based on the value of variable, it makes break window look like when you are dying in game (red spots): higher value, more red. I had problems with CSS and retina displays so I never fixed it ;/ 

So anyway, right now I would not implement "strict mode enforcement" - one change at time ;] but in future there could be some kind of strict mode via what you have described or style I described.  

An one last thing, I have not read your code yet, will find time after I come back from holidays.

**Comment by hovancik** [comment]
One problem I noticed: 
- break starts as normal
- user can postpone
- let's say it last 20 seconds till the end of break 
- user does `cmd+x`  

Should we skip break of postpone? I think that we should skip. What do you think?

**Comment by lundibundi** [comment]
@hovancik As for the first message

> I would only allow to edit settings by manually editing config file (I want to keep settings simple, and I do not think we need this settings on Settings page - the most of people I talked to never change any settings)

I'm completely fine with only having those options in config file, I'm used to editing it anyway).

> skipping should be enabled by default
number of allowed skips should be one (yeah, let's be harsh ;] )

That's fine, the only reason I set it to false was to preserve current behavior.

> Also not sure what about times: 2 and 5 minutes. Maybe both as 2 minutes?

**Comment by lundibundi** [comment]
@hovancik ping.

**Comment by hovancik** [comment]
Hi, sorry for late reply. I am super busy with another PR but no worries, I did not forget ;]

**Comment by hovancik** [comment]
I've just read related issue and our previous conversation. Uff ;] 

I'm still thinking about what do to with skip/postpone when the break is let's say at 80%. I'm beginning to think that ability to postpone should be available only first 10/20% of break time.. 

Let's say I'm 2 minutes into 5 minute break, I guess we can safely say that one does not want to postpone but skip? I am not sure...

**Comment by lundibundi** [comment]
This is truly a hard thing to define, but I think 10% should be okay (or maybe 20% as default to have it at 1 minute for default 5 min long break), as you usually don't need to postpone a break if half of it has already passed. I think we can also add a configuration option for this.

Though I think this should not be available for short breaks because they are short enough already.

**Comment by lundibundi** [comment]
Ok, so there is the case when you can pospone but you cannot skip (strictMode: true, breakPostponable: true), so what should we do in that case if the `breakPostponableDurationPercent` (what do you think about the name btw?) is reached?
I suggest that in this case we should allow to postpone for the whole duration of the event, so that later when user reaches postpone limit he will not have any option available (neither postpone nor skip). and will have to take a break (which is what strict for).

**Comment by hovancik** [comment]
The name is better than mine, I like it ;] I will try it out :+1:

**Comment by hovancik** [comment]
Sorry for delay, I would like to work on this now. I'll try to merge master in.

**Comment by hovancik** [comment]
I've created new branch, https://github.com/hovancik/stretchly/compare/master...feature/postpone 
Will need to test if merge was OK

**Pull request closed without merging**
