### PR TITLE
Add support for Flatpak

### PR DESCRIPTION
**Pull request by jwillikers**
Issue: #699

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [X]  issue was opened to discuss proposed changes before starting implementation. It is important do discuss changes before implementing them (Why should we add it? How should it work? How should it look? Where will it be? ...).
- [X]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [X]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [X]  app version number was not changed.
- [X]  all new code has tests to ensure against regressions.
- [X] `npm run lint` reports no offenses.
- [X] `npm run test` is error-free.
- [X]  README and CHANGELOG were updated accordingly.
- [X]  after PR is approved, all commits in it are [squashed](https://gitbetter.substack.com/p/how-to-squash-git-commits)

### Description of the Change

This PR adds the necessary changes to support distribution as a Flatpak on Flathub and it provides a development Flatpak manifest in this repository for building from the latest commit on `trunk`.

Flatpak's require a desktop file, so one has been added to repository named `net.hovancik.Stretchly.desktop`.
The development version of the Flatpak manifest, which is required to build the Flatpak, includes a `.Devel` suffix after the app-id and is named `net.hovancik.Stretchly.Devel.yaml`.
For the application to be distributed on Flathub, an AppStream metadata file has been created, named `net.hovancik.Stretchly.metainfo.xml`.
It's important that with each new release, the `releases` section in the AppStream metadata file is updated with at least a version and date of the release.
A description of the release is also helpful since users will be able to see this information when installing, browsing, or updating the app.

In order to be published on Flathub, a PR should be made by @hovancik to [flathub/flathub](https://github.com/flathub/flathub/) containing a release version of the Flatpak manifest.
I have a branch [here](https://github.com/jwillikers/flathub/tree/net.hovancik.Stretchly) with the release manifest which you can use for this to make it as simple as possible.

### Verification Process

I've documented the process for creating the development version of the Flatpak in the `build-flatpak.md`.
To test the current changes, you need to change the Git branch in the manifest to `flatpak` instead of `trunk.
Once this is merged, the manifest will pull from the latest commit on `trunk` as it should.
I've initially verified that I can build the Flatpak and run it and that the settings menu is accessible / generally usable.
It's important to verify the desktop file and AppStream metdata file are valid.
These can be validated as follows:

```
desktop-file-validate net.hovancik.Stretchly.desktop
flatpak run org.freedesktop.appstream-glib validate net.hovancik.Stretchly.metainfo.xml
```
I've added a GitHub CI workflow that can be used to verify these files, if desired.

Testing in an Ubuntu 20.04 VM, I've been able to get the app indicator to show up as a `...` but the image does not show up yet.

### Other information

I've put most of the files in the top-level, but these can be moved as seen fit.

### CODE REVIEW

**Comment by jwillikers** [comment]
Background colors are now working correctly in the Flatpak! :smile:

**Comment by jwillikers** [comment]
@hovancik I've gone ahead and refactored this PR to add everything necessary for submitting a Flathub repository for Stretchly. The `metainfo` and `.desktop` files can be kept here or stored in the Flathub repository. Either works, so that's up to you. The `metainfo` will need to be updated with release notes for each release. I have an initial branch prepared that can be submitted on Flathub to add the Stretchly repository when ready. The branch is [here](https://github.com/jwillikers/flathub/tree/net.hovancik.Stretchly).

**Comment by hovancik** [comment]
Ok, so what are the steps, then?

**Comment by jwillikers** [comment]
1. I'd recommend merging in this branch and cutting a new release as the first step.
2. After that, I can update my Flathub branch to point the latest release of Stretchly instead of this branch.
3. Once that is done, you should fork my [net.hovancik.Stretchly branch](https://github.com/jwillikers/flathub/tree/net.hovancik.Stretchly) and submit it as a PR to the [Flathub](https://github.com/flathub/flathub) repository.
4. I'll help out with the review process.

**Comment by hovancik** [comment]
Gotcha, I will try adding at least some bugfix or new feature and then merge this as well, so I don't have empty release.

**Comment by jwillikers** [comment]
> Gotcha, I will try adding at least some bugfix or new feature and then merge this as well, so I don't have empty release.

You'll just need to remember to update the `net.hovancik.Stretchly.metainfo.xml` file with the release details when you cut the release.

**Comment by hovancik** [comment]
@jwillikers I've created new release

**Comment by jwillikers** [comment]
@hovancik Awesome! I've updated my Flathub fork for your new release of Stretchly! I see you forked my fork, so just pull in my latest commits and then you should be good-to-go to submit a pull-request to `flathub/flathub`. 🥳🥳

**Comment by hovancik** [comment]
I can't do that :( 

image

**Comment by jwillikers** [comment]
@hovancik Sorry, try making the PR with the `base` branch on the left side set to `new-pr`.

**Comment by hovancik** [comment]
Thanks, https://github.com/flathub/flathub/pull/3529 :)

**Pull request merged**
