### PR TITLE
Migrate to vitest

### PR DESCRIPTION
**Pull request by cany748**
Issue: #1417 

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [x]  issue was opened to discuss proposed changes before starting implementation. It is important do discuss changes before implementing them (Why should we add it? How should it work? How should it look? Where will it be? ...).
- [x]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [ ]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [x]  app version number was not changed.
- [x]  all new code has tests to ensure against regressions.
- [x] `npm run lint` reports no offenses.
- [x] `npm run test` is error-free.
- [ ]  README and CHANGELOG were updated accordingly.
- [x]  after PR is approved, all commits in it are [squashed](https://gitbetter.substack.com/p/how-to-squash-git-commits)

### CODE REVIEW

**Comment by hovancik** [comment]
Thanks! Will need to find time to check the changes, but Coverage seems to not go through

**Comment by hovancik** [comment]
I am also getting `The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
`

**Comment by cany748** [comment]
> I am also getting `The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details. `

There's nothing wrong with that, electron now supports ESIM and it will be easy to switch in the future

**Comment by cany748** [comment]
I fixed the coverage, but there are some differences:

1. Vitest takes into account not only files in the app/utils folder, but also the entire app folder. This can be easily fixed by setting `coverage: { include: ["app/utils"] }`
2. Vitest also counts files without tests as 0% coverage. I believe this is the correct behavior, but if you disagree with me, this can also be changed via configuration.
3. We will need to create separate tests for the defaultBreakIdeas.js anddefaultMicrobreakIdeas.js files.

Otherwise, coverage is very similar

**Comment by hovancik** [comment]
Thanks! I don't really care about the coverage number, I usually only look on difference when having new commits so looks good!

**Pull request merged**
