### PR TITLE
i18n: update chinese (traditional) translation

### PR DESCRIPTION
**Pull request by pan93412**
Issue: #584

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [x]  issue was opened to discuss proposed changes before starting implementation.
- [x]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [x]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [x]  app version number was not changed.
- [x]  all new code has tests to ensure against regressions.
- [x] `npm run lint` reports no offenses.
- [ ] `npm run test` is error-free.
- [x]  README and CHANGELOG were updated accordingly.

### Description of the Change
Update Chinese (Traditional) translation for stretchly (redesigned).

### CODE REVIEW

**Comment by pan93412** [comment]
| k | v |
|:-:|:-:|
| glossary | [stretchly-glossary-0519.zip](https://github.com/hovancik/stretchly/files/4650114/stretchly-glossary-0519.zip) |

**Comment by pan93412** [comment]
@hovancik It appears like something wrong when I ran `npm run test`.

Looks like this isn't from me.

```
  85 passing (55s)
  1 failing

  1) UntilMorning
       Default Settings
         loadMorningTime() returns morning time:

      AssertionError: expected 22 to equal -2
      + expected - actual

      -22
      +-2
      
      at Context.<anonymous> (test/untilMorning.js:52:76)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

**Comment by hovancik** [comment]
@pan93412 you can ignore this error, for some reason this test only works in CI

**Comment by pan93412** [comment]
@hovancik Ok you can merge it

**Comment by hovancik** [comment]
@pan93412 let me check the changes, because github shows CZ and SK were changes as well

**Pull request merged**
