### PR TITLE
Recreate time in tray images

### LINKED ISSUE #1478: [Feature request]: More legible remaining time in tray icon
### Version

- [X] I'm using version 1.15.1

### Existing requests

- [X] I've checked Existing requests

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### Problem description

I have a hard time reading the number (for the remaining time to the next pause) in the tray icon.

### Possible solution

- Offer an option that does not have the Stretchly icon in the background
- Use a more legible font (e.g. make it bolder)
- Improve contrast between icon and font

### Alternative solutions

See possible solution, I added multiple options there

### Additional information

I checked the source code (too see if there is something I can do), but I did not find any script that created the many number variation icons (I guess those where created with some automation)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hovancik**
closes #1478

### CODE REVIEW

**Comment by Wikiwix** [comment]
The update is somewhat an improvement, but still not very legible and definitely not pretty.
I am currently looking into improving that based on that PR myself if that is okay for you?
I will concentrate on a monochrome aesthetic for now, I hope to have something to show soon.

A question that already came up for me:
- How/where are the SVG base files transformed to the base PNG files?
  Having that within the script might give additional possibilities and reduce the places icons are created from.

**Comment by hovancik** [comment]
> How/where are the SVG base files transformed to the base PNG files?

I believe I created them manually based on specifics for different OSes / trial error

**Comment by Wikiwix** [comment]
A very first draft looks like this: 
image

**Comment by Wikiwix** [comment]
I have adapted the code (locally and not cleaned up yet), for the icons to look like this:

image

@hovancik should I prepare a complete change using this approach or do you dislike it?

I made some other improvements on the way:
- limiting the width of the text
- really (vertically) centering the text based on its actual dimensions

**Comment by Wikiwix** [comment]
I add least put some of the change suggestions already into a branch (based on this branch): https://github.com/Wikiwix/stretchly/commit/b3927e1ebbcb48429cbea7cd1d95bd81c6ed073f

**Comment by hovancik** [comment]
Looks nice! Please go ahead :)

**Comment by Wikiwix** [comment]
> Looks nice! Please go ahead :)

Alright, I will try to prepare the PR within this week :)

Should I just make a PR targeting `trunk` or should I make a PR targeting this PR's feature branch?

**Comment by hovancik** [comment]
feel free going for trunk

**Comment by Wikiwix** [comment]
Created a new PR: #1502

**Pull request closed without merging**
