### PR TITLE
Updates Hindi translations

### PR DESCRIPTION
**Pull request by sunn-e**
Issue: #401 

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [x]  issue was opened to discuss proposed changes before starting implementation.
- [ ]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [ ]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [ ]  app version number was not changed.
- [ ]  all new code has tests to ensure against regressions.
- [ ] `npm run lint` reports no offenses.
- [ ] `npm run test` is error-free.
- [ ]  README and CHANGELOG were updated accordingly.

### Description of the Change

Corrected the translation and minor word fixes for easy reading.

### CODE REVIEW

**Comment by hovancik** [comment]
Thanks! Do you plan to add Marathi in the same PR?

**Comment by sunn-e** [comment]
No. I may have to consult with some of my friends to have best Marathi translation. It has some local dialects so I may become biased since I know standard marathi as well as one dialect(native speaker- Varhadi https://en.wikipedia.org/wiki/Varhadi_dialect) of it. It will take time. close this pr but keep #401 open. Also, please see if any native hindi speaker is interested in improving my transaltion further if thats possible. Otherwise you can merge this.

**Comment by sunn-e** [comment]
@hovancik  You can merge this. I will send Marathi version when I will be free. :)

**Comment by hovancik** [comment]
Thanks @sunn-e . Would you like to add yourself to readme and update changelog? 

https://github.com/hovancik/stretchly#contributors

**Comment by sunn-e** [comment]
How does one update changelog?

**Comment by hovancik** [comment]
@sunn-e I've done it for you and merged the PRs together ;]

**Pull request merged**
