### PR TITLE
Added All Relevant Image Assets for Paused Indicator

### PR DESCRIPTION
**Pull request by FanciestW**
Issue: #287 

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [X]  issue was opened to discuss proposed changes before starting implementation.
- [X]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [X]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [X]  app version number was not changed.
- [X]  all new code has tests to ensure against regressions.
- [X] `npm run lint` reports no offenses.
- [X] `npm run test` is error-free.
- [X]  README and CHANGELOG were updated accordingly.

### Description of the Change
Added images assets for paused indicators.

### CODE REVIEW

**Comment by hovancik** [comment]
I'm finished other things up, but will work on this before making new release so we get shiny logos ;]

**Comment by hovancik** [comment]
There are few things that you can help with ;] 

One is that I used the https://github.com/typefoo/node-icns to generate icons ( icns I believe) in https://github.com/hovancik/stretchly/tree/master/build. Package doesn't seems to exist anymore but there should be some another for sure ;] 

Then we can fix issue with icons on Linux  and more

**Comment by lixiawei** [comment]
cool app!!

**Comment by hovancik** [comment]
@FanciestW - I have started working on changes in new branch forked from yours (#386), so I am closing this PR. 

Do you have a svg for colorful paused icon? I'm missing that one ;]

**Pull request closed without merging**
