### PR TITLE
#667: preferences nav visible all time

### LINKED ISSUE #677: FR: preferences nav menu should be visible all the tiime - "position:fixed" (not scrollable with page)
### Prerequisites

- [x] I'm using latest version: v1.0.0 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

preferences nav menu should be visible all the tiime - "position:fixed" (not scrollable with page)

Operating system: any

### Steps to Reproduce

**Expected behavior:** 
preferences nav menu is allways shown at top
Zrzut ekranu z 2020-09-09 18-53-50

**Actual behavior:** preferences nav menu is scrollable
Zrzut ekranu z 2020-09-09 18-53-59

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### PR DESCRIPTION
**Pull request by mwoz123**
Issue: closes #677

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [ shortly, but yes]  issue was opened to discuss proposed changes before starting implementation.
- [x]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [x]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [x]  app version number was not changed.
- [x]  all new code has tests to ensure against regressions.
- [x] `npm run lint` reports no offenses.
- [x] `npm run test` is error-free.
- [x] README and CHANGELOG were updated accordingly.
- [x]  after PR is approved, all commits in it are [squashed](https://gitbetter.substack.com/p/how-to-squash-git-commits)

### Description of the Change

preferences nav menu visible all the tiime - "position:fixed" (not scrollable with page).
Now even when scrolled preferences can be quickly changed. 

Will be usefull for #667 (#680)

Zrzut ekranu z 2020-09-09 19-31-32
Zrzut ekranu z 2020-09-09 19-31-36
Zrzut ekranu z 2020-09-09 19-31-41
Zrzut ekranu z 2020-09-09 19-31-44
Zrzut ekranu z 2020-09-09 19-31-50

### CODE REVIEW

**Comment by hovancik** [comment]
Looks good! What OS did you test in? I am now testing Linux but will try macOS and Windows later.

**Comment by mwoz123** [comment]
Ubuntu 20.04 lts

**Review by hovancik — APPROVED** [review]
Feel free to squash and I'll merge :)

**Comment by mwoz123** [comment]
> Feel free to squash and I'll merge :)

Thanks:)

I've so problems with squash from commandline. 

Could you do it using github UI, during merge ? As on image below:

git ui merge


IMHO it seems to be saver option..

**Comment by hovancik** [comment]
Well, it used to be that Girhub would then give credits for the code to me then, but let's see...

**Pull request merged**
