### PR TITLE
Enabling/disabling Mini/Long Breaks resets the breaks

### PR DESCRIPTION
**Pull request by balazsnasz**
Issue: #503

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [X]  issue was opened to discuss proposed changes before starting implementation.
- [X]  during development, `node` version specified in `package.json` was used (ie using [nvm](https://github.com/creationix/nvm)).
- [X]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [X]  app version number was not changed.
- [ ]  all new code has tests to ensure against regressions.
- [X] `npm run lint` reports no offenses.
- [X] `npm run test` is error-free.
- [X]  README and CHANGELOG were updated accordingly.

### Description of the Change
Enabling/disabling Mini/Long Breaks resets the breaks (#503)

### CODE REVIEW

**Comment by hovancik** [comment]
Let me check because there are few possible places to do this ;]

**Comment by hovancik** [comment]
I think I would like to have more complex solution. First thoughts: 
- it should be in `main.js` `ipcMain.on('save-setting', function (event, key, value) {` where I do specific stuff for specific settings, so it's kept in same place as other special things
- I think we should probably have special class in utils to handle changes, so that we can test it, depends how much code it ends up having (and if there's even a way how we could test it)

Some quick pseudo (could be some methods that we call in `save-settings`)

```
- when enable/disable break is changed
  - check if next scheduled is enabled  
    and remove from scheduler, schedule next enabled if needed
- when enable/disable notification is changed
   - check what's next and schedule next break with/without notification
```
with scheduling new break I would like to consider how much time has already passed, so if next scheduled break is Mini in 5 minutes, and we are disabling notification, it will be in 5 mins but without notification   

What do you think?

**Comment by balazsnasz** [comment]
Are you sure you want to make this so complex?
Change such settings are not a too regular thing.

**Comment by hovancik** [comment]
Well, I am not sure :D But I think it's expected. 

Let's say when I am 1 minute to Mini and I disable Long, it's unexpected that breaks are reset.

**Pull request closed without merging**
