### PR TITLE
add a language

### PR DESCRIPTION
**Pull request by wilicw**
I add chinese,and add language selection function, but in the idea that there is a mistake, trouble you to repair, I hope you can use the request

### CODE REVIEW

**Comment by hovancik** [comment]
Hi and thanks for the input! 

Translations are on my TODO list and some people already opened issues about it: #136, #108. Your implemntation is not bad, but I think we should go with something "nodejs". I'm not familiar myself with nodejs internationalization, but there seems to be some packages: https://github.com/mashpie/i18n-node, https://github.com/i18next/i18next, https://github.com/martinheidegger/i18n-core. Some people recommended https://www.gnu.org/software/gettext/. 

We also need to think about how we wanna translate, as there are also online tools like https://crowdin.com/ or https://weblate.org/en/.

**Comment by wilicw** [comment]
Thank you for your reply, I think I can help you translate into Chinese in the future😀

**Comment by hovancik** [comment]
If you are interested, we could work on this together.

**Comment by midpoint** [comment]
[chinese.zip](https://github.com/hovancik/stretchly/files/1390213/chinese.zip)
This is my production of Chinese package,unpack  it to resources folder.

**Comment by hovancik** [comment]
The interface are now in master, feel free to make a PR with translation file.

**Pull request closed without merging**
