### PR TITLE
Korean locale addition and fixing typo

### PR DESCRIPTION
**Pull request by dnjstlr555**
Issue: #

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [ ]  issue was opened to discuss proposed changes before starting implementation.
- [ ]  during development, `node` version specified in `package.json` was used.
- [ ]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [ ]  app version number was not changed.
- [ ]  all new code has tests to ensure against regressions.
- [ ] `npm run lint` reports no offenses.
- [ ] `npm run test` is error-free.
- [ ]  README and CHANGELOG were updated accordingly.

### Description of the Change
Korean locale addition and fix typo in en.json

### CODE REVIEW

**Comment by dnjstlr555** [comment]
So what is "welcome window does not open after first run" hook? seems its not related with my commits.

**Comment by dnjstlr555** [comment]
huh. I think AppVeyor thing builds everything based on luck.

**Comment by hovancik** [comment]
Yeah, tests seems to be "random" sometimes. 

I've added some missing stuff. Do you know how to test your translations locally?

**Comment by dnjstlr555** [comment]
@hovancik I don't know. I never knew using node.js like this way. How to build it?

**Comment by dnjstlr555** [comment]
oop nevermind

**Comment by hovancik** [comment]
if you tell me what is your OS, I could build a version for you to test

**Comment by hovancik** [comment]
any update? @dnjstlr555

**Comment by dnjstlr555** [comment]
@hovancik I'm so sorry. I was too busy these days. I'm working on design because my locale change makes mess up its default fonts and I replaced it with open font. I'll update more in an hour.

**Comment by hovancik** [comment]
Hi, what do you mean by design? On my system fonts look ok. We should not replace fonts, that's huge change.

**Comment by dnjstlr555** [comment]
closing pull request, it's too old and I'm going to restart all again

**Comment by hovancik** [comment]
:+1:

**Pull request closed without merging**
