### PR TITLE
Fixed italian translation typos, plus minor adjustments

### PR DESCRIPTION
**Pull request by Jackymancs4**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [ ]  issue was opened to discuss proposed changes before starting implementation.
- [x]  during development, `node` version specified in `package.json` was used.
- [x]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [x]  app version number was not changed.
- [ ]  all new code has tests to ensure against regressions.
- [x] `npm run lint` reports no offenses.
- [x] `npm run test` is error-free.
- [ ]  README and CHANGELOG were updated accordingly.

### Description of the Change

Hello @hovancik 
I'm quite a fan of your work.
I saw you merged #312 before I was able to comment about a couple of issues in it.
Here I fixed two typos and rephrased some sentences to make them more in line with the english version.

Also I was not really happy about replacing ```...``` with character U+2026 ```…``` (for [references](http://graphemica.com/%E2%80%A6)), mainly because the english locale file (the reference version) use the simple three point ellipsis. So I reverted that, too. Obviously discussion is welcome.

Ping to @cgand

### CODE REVIEW

**Comment by cgand** [comment]
Thanks @Jackymancs4 for correcting Italian typos. About ellipses I think that must be keeped and that must applied at all translation (not reverting to wrong ones).
For the rephrased sentence "comunque perché non controllarle?" no problem for your more in line version.

**Comment by hovancik** [comment]
@cgand why are they wrong? I mean ...

**Comment by cgand** [comment]
> @cgand why are they wrong? I mean ...

Using ellipses _(press Option-; on a US keyboard)_ is generally a good typographic practice for the 3 periods (recommended by [Standard Ebooks Typographic manual)](https://standardebooks.org/contribute/typography). Quite sure software by Apple use it.
Ellipses are used in all menu by Xcode when you create a new macOS app.

See gif:
https://cl.ly/a2370c95cb8f

**Comment by cgand** [comment]
> If Italian translations are ok, I am happy to merge.
Yes @Jackymancs4 corrections are OK.
Thanks both.

**Comment by Jackymancs4** [comment]
> Using ellipses (press Option-; on a US keyboard) is generally a good typographic practice for the 3 periods (recommended by Standard Ebooks Typographic manual). Quite sure software by Apple use it.
Ellipses are used in all menu by Xcode when you create a new macOS app.

Never stop learning something new. Thanks @cgand 

> If Italian translations are ok, I am happy to merge.

I'm also fine with it. LGTM ;)

**Comment by hovancik** [comment]
Just one thing, @Jackymancs4  please add yourself to the https://github.com/hovancik/stretchly#contributors ;]

**Pull request merged**
