### PR TITLE
Single page settings

### PR DESCRIPTION
**Pull request by Jackymancs4**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [ ]  issue was opened to discuss proposed changes before starting implementation.
- [x]  during development, `node` version specified in `package.json` was used.
- [x]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [x]  app version number was not changed.
- [ ]  all new code has tests to ensure against regressions.
- [ ] `npm run lint` reports no offenses.
- [x] `npm run test` is error-free.
- [ ]  README and CHANGELOG were updated accordingly.

### Description of the Change

I unified all settings pages under a single one, with one main script handling it.
The internal semantic division is kept mostly unchanged, so settings are still treated in three separated groups (settings, settings2, settings3).

To keep the very same layout, I implemented a purely CSS carousel following this [tutorial](https://codeburst.io/how-to-pure-css-carousel-ce1a8cb231c8).

Now scrolling through the settings panes is smooth thanks to the customizable CSS transition function, and doesn't require the new page load lag anymore.

### Other information

|Before|After|
|--|--|
|schermata 2018-10-27 alle 16 54 40|schermata 2018-10-27 alle 16 54 12|

If required I can post a recording of the changes applied.
If and when merged, the next step could be refactoring the slighlty big settings file.
Sorry for not opening a dedicated issue before, it's really been a quick idea that worked out good.

### CODE REVIEW

**Comment by hovancik** [comment]
Thanks, I will test it around ;]

**Comment by hovancik** [comment]
I like it, but there are some problems I have found: 

screenshot_2018-11-03_17-22-44 

on first 2 pages I have some scrollbar at the bottom, but not on 3th and it makes page jump a bit 

Also when you change the language on 3th page it jumps to the 1st page

**Comment by Jackymancs4** [comment]
So, two bugs:

1. - [ ] on first 2 pages I have some scrollbar at the bottom, but not on 3th and it makes page jump a bit
2. - [ ] when you change the language on 3th page it jumps to the 1st page

I'm able to replicate both.

1. easy to fix, patch on its way
2. this one seems tricky. 

I have not investigated yet how you (or i18next) propagate the new language data, but it seems to me like a page refresh, in which case I'm not sure how to retain the panes status. If this is a strict requirement I'll need a couple days to think about it.

**Comment by hovancik** [comment]
Yeah, I think when we change the language, we wanna stay at the same page. You might be able to do that with # link. 

How difficult would be to add one more page to settings?

**Comment by hovancik** [comment]
Reworking the settings based on designs from designer so closing this one.

**Pull request closed without merging**
