### PR TITLE
Fix text readability, change from hairline/light/thin to regular/bold

### PR DESCRIPTION
**Pull request by jancborchardt**
Issue: #57

Specifically the part

> A lot of the text is too hard to read because it its thinness and bad contrast.

### Requirements

- [ ]  issue was opened to discuss proposed changes before starting implementation.
   - I didn’t specifically open an issue, but the existing #57 already mentioned the problem.
- [x]  during development, `node` version specified in `package.json` was used.
- [x]  package versions and package-lock.json were not changed (`npm install --no-save`).
- [x]  app version number was not changed.
- [ ]  all new code has tests to ensure against regressions.
   - Wasn’t sure how to best test loop through all the breaks and microbreaks. The indicator icon to get to the settings was not shown in development (am on Ubuntu).
- [x] `npm run lint` reports no offenses.
- [x] `npm run test` is error-free.
- [ ]  README and CHANGELOG were updated accordingly.
   - Didn’t take new screenshots of all the pages.

### Description of the Change

The hairline, thin and light font weights make the text very difficult to read and result in subpar contrast on basically on the colors. You should be able to read the break suggestions quickly so you can perform them, and not harm your eyes further.

That’s why the font weights were replaced with higher weights from the same font, Lato:
- Hairline to Regular
- Thin and Light to Bold (also to not have too many different weights which are almost the same anyway)

I downloaded Lato from Google Fonts and it only included the ttf. If all the other formats are indeed needed, let me know where you downloaded them from and I’ll add the files for Regular and Bold.

### Verification Process

I checked out the initial run window and it looked good. Can’t make it show up again though to take screenshots, and can’t loop through the break suggestions or show the settings window as mentioned above. :\ Let me know how it works and I’ll continue with that. :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
The Appveyor failure seems to be unrelated to this change as only CSS and font files were touched? https://ci.appveyor.com/project/hovancik/stretchly/build/1.0.1021/job/qiqjt37x16ai3xrs

**Comment by hovancik** [comment]
Yeah, appveyor seems to fails tests on random lately. 

You might need https://github.com/hovancik/stretchly#linux-note to get tray working correctly on Linux. 

Here is what I am getting on Linux with current version: 

screenshot_2018-09-23_11-04-21

and on mac: 

stretchly-break

and with your change it looks like this (on Linux):

screenshot_2018-09-23_11-13-27
 
so this is something platform specific... Maybe some font related CSS? I'm not sure what mac/linux/windows are doing differently when rendering fonts, but I think that's where solution might be. What do you think?

**Comment by hovancik** [comment]
this is mac: 
screen shot 2018-09-23 at 16 10 09

**Comment by jancborchardt** [comment]
I would definitely say it’s way easier to read. Yes, on macOS it seems less bad in the current version than on Linux (which I am using), but still thin fonts are not ideal.

I would actually do additional things like:
- Bold the heading (regular for body text) for better separation – **this relates a lot with this pull request**
- Possibly cut down the text and improve wording of each break so there’s less to read
- Making the body text left-aligned for even more readability
- Introduce a symbol (maybe emoji) to show for each activity to even more quickly see what it’s about

And all of these would change the look quite a lot – but it’s best to do stuff step-by-step so it’s easier to review and discuss. So yes, I definitely think that this pull request is a step in the right direction, but it’s only the first one.

What do you think?

**Comment by hovancik** [comment]
I've created #304 and tested on win, amc, debian. Thanks for bringing this issue forward ;]

**Pull request closed without merging**
